config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: %i[index new create]
  resources :favorites, only: %i[create destroy]
  resources :restaurants, only: %i[show index]
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/load', to: 'restaurants#load'
  get '/verify', to: 'restaurants#verify'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/about.html.erb
<div class="card">
  <div class="card-body">
    <h1><u>About</u></h1>
    <br>
    <h2>What Is Randomeal?</h2>

    <p align="left">Randomeal will randomly generate the perfect restaurant that not only meets your party’s needs, but gets you out into your city so that you can explore new restaurants in new neighborhoods for brand new experiences.</p>

    <h2>How Does It Work?</h2>

    <p align="left">

    <strong>Step 1)</strong> Input filters such as favourites, dislikes, price and your desired location. <br>

    <strong>Step 2)</strong> Hit randomize! Let Randomeal provide you with the ideal restaurant! <br>

    <strong>Step 3)</strong> Either go forward with the generated restaurant or hit “Randomize” to see another! <br>

    <strong>Step 4)</strong> Lets eat! After making your selection, you will be provided with all of the information of the restaurant!</p>
   </div>
 </div>

app/views/pages/contact.html.erb
<div class="card">
  <div class="card-body">
<h1>Contact Us</h1>

<p>Please leave your details and query below and we'll get back to you as soon as possible...</p>

  <%= simple_form_for :form do |f| %>
    <%= f.input :email %>
    <%= f.input :comments %>
    <%= link_to 'submit', root_path, class: 'btn', style: "background-color: #F3613A; color: white"%>
  <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="card">
  <div class="card-body">
    <p class="feature-header">Your location:</p>

    <%= text_field_tag :address, "", id: "address-input", placeholder: "Enter your address" %>

    <%= form_with url: root_path, method: "GET", remote: true, id: "hidden_form" do |f| %>
      <%= text_field_tag :latitude, nil, id: "lat", class: "hidden" %>
      <%= text_field_tag :longitude, nil, id: "long", class: "hidden" %>
      <%= submit_tag "submit", class: "hidden" %>
    <% end %>

    <div class="slidecontainer">
      <p class="feature-header">Distance: <span id="demo"></span> km</p>
      <input type="range" min="1" max="30" value="15" class="slider" id="myRange">
    </div>

    <button class="btn btn-primary mt-4" id="btn-randomeal-cat" type="button" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
      Not in the mood for <i class="fas fa-angle-down"></i>
    </button>
    <div class="collapse" id="collapseExample">
      <div class="" id="categories-div">
        <div class="categories-grid btn-group btn-group-toggle" data-toggle="buttons">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://www.yorkshireeveningpost.co.uk/images-a.jpimedia.uk/imagefetch/http://www.yorkshireeveningpost.co.uk/webimage/Prestige.Item.1.93033352!image/image.jpg?width=640)">
            Cafe
          </button>
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://portalbr.akamaized.net/brasil/uploads/2008/03/22134341/fast-food.jpg)">
            Fast Food
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://img.stpu.com.br/?img=https://s3.amazonaws.com/pu-mgr/default/a0R0f000010xA7GEAU/5c489cd8e4b0842c9b1b6c10.jpg&w=710&h=462)">
            Pizza
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://img.jakpost.net/c/2017/02/28/2017_02_28_22453_1488267265._large.jpg)">
            Japanese
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://cdnimg.webstaurantstore.com/uploads/buying_guide/2014/11/barfood-beerchicken.jpg)">
            Bar
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://gulamia.com.br/wp-content/uploads/2018/09/ultimo-dia-do-camemburger-no-cliente-hamburgueriatradi-hambueguer-180g-queijo-camember-empanado.jpg)">
            Burger
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://cdn-image.foodandwine.com/sites/default/files/styles/4_3_horizontal_-_1200x900/public/rib-eye-steak-au-poivre-xl-200202.jpg?itok=V64uhOvr)">
            Steak
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://media-cdn.tripadvisor.com/media/photo-s/18/3a/09/6c/bonefish-seafood-platter.jpg)">
            Seafood
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://img.manoramaonline.com/content/dam/mm/en/food/foodie/images/2020/1/26/lasagna.jpg)">
            Italian
          </button type="button">
          <button type="button" class="category category-grow" data-toggle="button" aria-pressed="false" autocomplete="off" style="background-image: url(https://images.immediate.co.uk/production/volatile/sites/2/2016/08/25471.jpg?quality=90&resize=600%2C400)">
            Vegetarian
          </button type="button">

        </div>
      </div>
    </div>

    <p class="feature-header">Price:</p>
    <div class="btn-group" role="group" aria-label="Basic example">
      <p id="price1" class="price-range py-2 px-3">$</p>
      <p id="price2" class="price-range py-2 px-3">$$</p>
      <p id="price3" class="price-range py-2 px-3">$$$</p>
      <p id="price4" class="price-range py-2 px-3">$$$$</p>
    </div>


    <%= simple_form_for(:restaurants, method: :GET, url: load_path) do |f| %>
      <%= f.input :categories, as: :string, input_html: {class: "form-control hidden", id: "category-hidden" }, required: false, label: false %>
      <%= f.input :price, as: :string, input_html: {class: "form-control hidden", id: "price-hidden" }, required: false, label: false %>
      <%= f.input :user_address, as: :string, input_html: {class: "form-control hidden", id: "user_address" }, label: false, required: true, value: @user_address ? @user_address : "" %>
      <%= f.input :distance, as: :string, input_html: {class: "form-control hidden", id: "distance", value: 15 }, label: false, required: false %>
      <%= f.button :submit, "Randomize", class: "btn btn-lg mt-3", id: "randomize-btn" %>
    <% end %>

  </div>
</div>

<script>
  function success(position) {
    const hiddenForm = document.getElementById("hidden_form");
    document.getElementById("lat").value = position.coords.latitude;
    document.getElementById("long").value = position.coords.longitude;
    Rails.fire(hiddenForm, 'submit');
  }

  <% unless params[:latitude].present? %>
    navigator.geolocation.getCurrentPosition(success);
  <% end %>

  document.getElementById("address-input").addEventListener("blur", (e) => {
    if (e.currentTarget.value) {
      document.getElementById("user_address").value = e.currentTarget.value;
    }
  })
</script>

app/views/pages/home.js.erb
document.getElementById("address-input").value = "<%= @user_address %>";
document.getElementById("user_address").value = "<%= @user_address %>";