config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, except: %i[index new create]
  resources :favorites, only: %i[create destroy]
  resources :restaurants, only: %i[show index]
  root to: 'pages#home'
  get '/about', to: 'pages#about'
  get '/contact', to: 'pages#contact'
  get '/load', to: 'restaurants#load'
  get '/verify', to: 'restaurants#verify'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :category
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  has_many :favorites, dependent: :destroy
end

app/controllers/restaurants_controller.rb
require 'open-uri'
require 'nokogiri'
require 'sidekiq'
require 'sidekiq-status'

class RestaurantsController < ApplicationController

  skip_before_action :authenticate_user!
  before_action :filtering_restaurants, only: [:index, :verify]

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def index
    @markers = {
      lat: @restaurant.latitude,
      lng: @restaurant.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { restaurant: @restaurant })
    }
  end

  def load
    geocoder_obj = Geocoder.search(params[:restaurants][:user_address]).first.data
    $location = [geocoder_obj["lat"].to_f, geocoder_obj["lon"].to_f]
    session[:category] = params[:restaurants][:categories]
    session[:price] = params[:restaurants][:price]
    session[:lat] = geocoder_obj["lat"].to_f
    session[:long] = geocoder_obj["lon"].to_f
    session[:distance] = params[:restaurants][:distance]
    # session[:sidekiq_job_id] = CreateRestaurantsJob.perform_later(location)
  end

  def verify
    parse
    render json: {
      found: true,
    }
  end

  private

  def filtering_restaurants
    @restaurants = Restaurant.all
    location = [session[:lat].to_f, session[:long].to_f]

    if session[:price].present?
      prices = [1,2,3,4] - session[:price].split(",").map { |price| price.to_i }
      @restaurants -= Restaurant.where(price_range: prices)
    end
    if session[:category].present?
      categories = session[:category].split(",")
      if categories.include?("Bar")
        categories << "Bar Food"
        categories << "Bars"
      end
      if categories.include?("Cafe")
        categories << "Café"
        categories << "Cafe Food"
        categories << "Coffee Bar"
        categories << "Coffee Shop"
        categories << "Caffe"
        categories << "Caffé"
        categories << "Cafe Bar"
        categories << "Café Bar"
        categories << "Cafés"
      end
      if categories.include?("Fast Food")
        categories << "Snack Bar"
      end
      if categories.include?("Japanese")
        categories << "Sushi"
        categories << "Lamen Shop"
      end
      if categories.include?("Burger")
        categories << "Burgers"
      end
      if categories.include?("Steak")
        categories << "Steakhouse"
        categories << "Grill"
        categories << "Churrascaria"
      end
      if categories.include?("Seafood")
        categories << "Sea Food"
      end
      if categories.include?("Vegetarian")
        categories << "Vegan"
      end
      categories_instances = Category.where(name: categories)
      @restaurants -= Restaurant.where(category_id: categories_instances)
    end
    if session[:distance].present?
      if @restaurants.any?
        @restaurants = @restaurants.reject do |rest|
          rest.latitude.nil? || rest.distance_to([session[:lat], session[:long]]) > session[:distance].to_i
        end
      end
    end
    @restaurant = @restaurants.sample
  end

  def parse
    start = 0
    counter = 0
    hash = {}

    5.times do

      url = "https://www.yelp.com/search?find_desc=Restaurants&find_loc=#{$location[0]} #{$location[1]}&start=#{start}"
      # url = "https://www.yelp.com/search?find_desc=Restaurants&find_loc=groningen&start=#{start}"
      email = "#{rand(99999..999999999999)}@gmail.com"
      html_file = open(url, "User-Agent" => "Ruby/2.6.5",
          "From" => email,
          "Referer" => "http://www.ruby-lang.org/").read
      html_doc = Nokogiri::HTML(html_file)

      break if html_doc.search("h3").first.text.include?("We're sorry, the page of results you requested is unavailable.")

      css_class = "li.lemon--li__373c0__1r9wz > div.lemon--div__373c0__1mboc > div.lemon--div__373c0__1mboc"

      html_doc.search(css_class).each_with_index do |element, index|

        next if element.search('.lemon--span__373c0__3997G .priceRange__373c0__2DY87').empty?

        hash[counter.to_s] = {}

        element.search('.lemon--h4__373c0__1yd__').each do |el|
          hash[counter.to_s]["name"] = el.text.gsub(/[[0-9].]/, "")[1..-1]
        end

        element.search('.lemon--p__373c0__3Qnnj .lemon--span__373c0__3997G').each do |el|
          hash[counter.to_s]["address"] = el.text unless el.text.include?("Miles") ||  el.text.include?("Offers") ||  el.text.include?("more")
        end

        element.search('.lemon--span__373c0__3997G .priceRange__373c0__2DY87').each do |el|
          hash[counter.to_s]["price"] = el.text.size
        end

        hash[counter.to_s]["category"] = element.search('.lemon--span__373c0__3997G .lemon--span__373c0__3997G .lemon--a__373c0__IEZFH').map(&:text).join(",")

        element.search('.lemon--a__373c0__IEZFH .lemon--img__373c0__3GQUb').each do |el|
          hash[counter.to_s]["photo"] = el.attribute('src').value if el.attribute('src').value.include?("bphoto")
        end

        element.search('.lemon--span__373c0__3997G .i-stars__373c0__tb0kH').each do |el|
          hash[counter.to_s]["rating"] = el.values[-2][0..-13].to_f
        end
        counter += 1
      end
      start += 30
      hash.each do |key, _value|
        hash[key]["category"].split(",").each do |category|
          Category.find_or_create_by(name: category)
        end
      end

      hash.each do |key, _value|
        Restaurant.find_or_create_by(
          name: hash[key]["name"],
          address: hash[key]["address"],
          rating: hash[key]["rating"],
          price_range: hash[key]["price"],
          image: hash[key]["photo"],
          category_id: Category.find_by(name: hash[key]["category"].split(",")[0]).id
        )
      end
    end
  end

end

app/views/restaurants/_info_window.html.erb
<h6><%= restaurant.name %></h6>
<p><%= restaurant.address %></p>

app/views/restaurants/index.html.erb
<% unless @restaurants == [] %>
  <div class="card" >
    <div class="card-body">
      <div class="card-btns">
        <%= link_to "<i class='fas fa-arrow-left text-left randomeal-secondary'></i>".html_safe, root_path%>
        <%= link_to "Randomize", restaurants_path(restaurants: {price: session[:price], categories: session[:categories], distance: session[:distance]}), class: "btn mt-0", id: "randomize-btn" %>
      </div>
    <div align="center">
      <div
        id="map"
        style="width: 90%;
        height: 240px;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
      </div>

      <h5 class="card-header"><%= @restaurant.name %></h5>

      <p class="card-text"><%= @restaurant.category.name %></p>
        <% price = "" %>
        <% @restaurant.price_range.to_i.times do %>
          <% price += "$ " %>
        <% end %>
      <p class="card-text border-bottom"><strong><%= price %></strong></p>
    </div>
    <div class="d-flex">
      <%= link_to "Let's go!", "https://www.google.com/maps/place/#{@restaurant.address}", target: "_blank", id: "go_to", class: "btn custom-btn-primary mt-2" %>
      <%= simple_form_for @favorite do |f| %>
        <% if current_user %>
          <%= f.button :submit, 'S2' %>
        <% end %>
      <% end %>
    </div>
    </div>
  </div>
<% else %>
  <h2>No restaurants match search criteria.</h2>
  <%= link_to "Back", root_path, class: "btn btn-lg mt-5", style: "background-color: #F3613A; color: white" %>
<% end %>

app/views/restaurants/load.html.erb
<p class="load-header">
  <span id="typing-animation"></span>
</p>
<%= image_tag 'randomeal-logo.png', class: "load-logo mb-5"  %>

<p class="load-footer">Powered by Sidekiq <i class="far fa-registered"></i></p>


<script>

  // const now = new Date()

  // const refresh = () => {
  //   if (new Date() - now > 25000) {
  //     window.location = "<%= root_path %>"
  //   }
  //   Rails.ajax({
  //     url: "<%= verify_path %>",
  //     type: "GET",
  //     success: function(data) {
  //       if (data.found == true) {
  //         window.location = "<%= restaurants_path %>";
  //       }
  //     }
  //   });
  // };

  Rails.ajax({
      url: "<%= verify_path %>",
      type: "GET",
      success: function(data) {
        if (data.found == true) {
          window.location = "<%= restaurants_path %>";
        }
      }
    });

  // setInterval(refresh, 1000);
</script>

app/views/restaurants/show.html.erb
<h1>Restaurants#show</h1>
<p>Find me in app/views/restaurants/show.html.erb</p>
<h2><%= @restaurant.name %></h2>
<%= image_tag (@restaurant.image) %>